/*
* Advanced weighting script X
* Wraith - Game extraction tools
*/

global proc WraithMesh_e51324b8_00_BindFunc()
{
   select -r WraithMesh_e51324b8_00;
   select -add j_bolt;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_00");

   skinPercent -tv j_bolt 1.0 $clu WraithMesh_e51324b8_00.vtx[0:217];
}

global proc WraithMesh_e51324b8_01_BindFunc()
{
   select -r WraithMesh_e51324b8_01;
   select -add j_gun;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_01");

   skinPercent -tv j_gun 1.0 $clu WraithMesh_e51324b8_01.vtx[0:496];
}

global proc WraithMesh_e51324b8_02_BindFunc()
{
   select -r WraithMesh_e51324b8_02;
   select -add tag_rem700_scope;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_02");

   skinPercent -tv tag_rem700_scope 1.0 $clu WraithMesh_e51324b8_02.vtx[0:457];
}

global proc WraithMesh_e51324b8_03_BindFunc()
{
   select -r WraithMesh_e51324b8_03;
   select -add bullet_joint;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_03");

   skinPercent -tv bullet_joint 1.0 $clu WraithMesh_e51324b8_03.vtx[0:44];
}

global proc WraithMesh_e51324b8_04_BindFunc()
{
   select -r WraithMesh_e51324b8_04;
   select -add tag_rem700_scope;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_04");

   skinPercent -tv tag_rem700_scope 1.0 $clu WraithMesh_e51324b8_04.vtx[0:12];
}

global proc WraithMesh_e51324b8_05_BindFunc()
{
   select -r WraithMesh_e51324b8_05;
   select -add tag_acog;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_05");

   skinPercent -tv tag_acog 1.0 $clu WraithMesh_e51324b8_05.vtx[0:738];
}

global proc WraithMesh_e51324b8_06_BindFunc()
{
   select -r WraithMesh_e51324b8_06;
   select -add tag_acog;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_06");

   skinPercent -tv tag_acog 1.0 $clu WraithMesh_e51324b8_06.vtx[0:47];
}

global proc WraithMesh_e51324b8_07_BindFunc()
{
   select -r WraithMesh_e51324b8_07;
   select -add tag_acog;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_07");

   skinPercent -tv tag_acog 1.0 $clu WraithMesh_e51324b8_07.vtx[0:8];
}

global proc WraithMesh_e51324b8_08_BindFunc()
{
   select -r WraithMesh_e51324b8_08;
   select -add tag_acog;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_e51324b8_08");

   skinPercent -tv tag_acog 1.0 $clu WraithMesh_e51324b8_08.vtx[0:7];
}

global proc RunAdvancedScript()
{
   catch(WraithMesh_e51324b8_00_BindFunc());
   catch(WraithMesh_e51324b8_01_BindFunc());
   catch(WraithMesh_e51324b8_02_BindFunc());
   catch(WraithMesh_e51324b8_03_BindFunc());
   catch(WraithMesh_e51324b8_04_BindFunc());
   catch(WraithMesh_e51324b8_05_BindFunc());
   catch(WraithMesh_e51324b8_06_BindFunc());
   catch(WraithMesh_e51324b8_07_BindFunc());
   catch(WraithMesh_e51324b8_08_BindFunc());
}

global proc NamespacePurge()
{
   string $allNodes[] = `ls`;
   for($node in $allNodes) {
      string $buffer[];
      tokenize $node ":" $buffer;
      string $newName = $buffer[size($buffer)-1];
       catchQuiet(`rename $node $newName`);
   }
}

print("Currently binding the current model, please wait...\n");
NamespacePurge();
RunAdvancedScript();
print("The model has been binded.\n");

