/*
* Advanced weighting script X
* Wraith - Game extraction tools
*/

global proc WraithMesh_a66ffae9_00_BindFunc()
{
   select -r WraithMesh_a66ffae9_00;
   select -add tag_weapon;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_a66ffae9_00");

   skinPercent -tv tag_weapon 1.0 $clu WraithMesh_a66ffae9_00.vtx[0:855];
}

global proc WraithMesh_a66ffae9_01_BindFunc()
{
   select -r WraithMesh_a66ffae9_01;
   select -add tag_weapon;
   newSkinCluster "-toSelectedBones -mi 30 -omi true -dr 5.0 -rui false";   string $clu = findRelatedSkinCluster("WraithMesh_a66ffae9_01");

   skinPercent -tv tag_weapon 1.0 $clu WraithMesh_a66ffae9_01.vtx[0:16];
}

global proc RunAdvancedScript()
{
   catch(WraithMesh_a66ffae9_00_BindFunc());
   catch(WraithMesh_a66ffae9_01_BindFunc());
}

global proc NamespacePurge()
{
   string $allNodes[] = `ls`;
   for($node in $allNodes) {
      string $buffer[];
      tokenize $node ":" $buffer;
      string $newName = $buffer[size($buffer)-1];
       catchQuiet(`rename $node $newName`);
   }
}

print("Currently binding the current model, please wait...\n");
NamespacePurge();
RunAdvancedScript();
print("The model has been binded.\n");

